version: '3'

services:
  ##
  ## CONTAINER for Client Side Application
  ## to test service run:
  ##     docker-compose up --build -d client
  ## ----------------------------------------
  client:
    build: 
      context: ./
    # environment:
      # - REACT_APP_PORT=${REACT_APP_PORT}
      # - CHOKIDAR_USEPOLLING=true # supposed to help with watch events in VM https://create-react-app.dev/docs/advanced-configuration
    ports:
      - 3001:3000 # expose ports - HOST:CONTAINER
      - 35729:35729
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: npm run client
