version: '3'

services:
  ##
  ## CONTAINER for Client Side Application
  ## to test service run:
  ##     docker-compose up --build -d client
  ## ----------------------------------------
  client:
    build: 
      context: ./
    ports:
      - 3001:3000 # expose ports - HOST:CONTAINER (for create-react-app)
      - 35729:35729 # expose ports - HOST:CONTAINER (for serviceworker warm reloading)
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: npm start
